### ISSUE TITLE
SyntaxError: Deleting local variable in strict mode

### ISSUE THREAD

**Issue by oncletom** [unassert-js/unassertify#5]
Hello,

I have tried `unassertify` with `tinyify` but I stumble on the following error with this command:

```bash
browserify -p tinyify -o static/bundle.js static/assets/js/main.js
```

```
/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2651
  throw err
  ^

SyntaxError: Deleting local variable in strict mode (56:6)
    at Parser.pp$4.raise (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2649:13)
    at Parser.pp$3.parseMaybeUnary (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1941:14)
    at Parser.pp$3.parseExprOps (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1887:19)
    at Parser.pp$3.parseMaybeConditional (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1870:19)
    at Parser.pp$3.parseMaybeAssign (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1845:19)
    at Parser.pp$3.parseExpression (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1816:19)
    at Parser.pp$1.parseStatement (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:798:45)
    at Parser.pp$1.parseBlock (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1077:23)
    at Parser.pp$1.parseStatement (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:775:34)
    at Parser.pp$1.parseIfStatement (/Users/oncletom/workspace/emunova/emunova.net/node_modules/unassertify/node_modules/acorn/dist/acorn.js:902:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! emunova.net@3.3.2 build:js: `browserify -p tinyify -o static/bundle.js static/assets/js/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the emunova.net@3.3.2 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oncletom/.npm/_logs/2017-11-20T08_41_40_243Z-debug.log
```

I don't use `assert` in my code directly so I'm unsure why this exception is thrown.

**Comment by twada** [comment]
@oncletom Thank you for reporting!
It's a bit difficult to reproduce so would you create a small reproduction case repository?
